src/cart/urls.py
from django.urls import path
from .views import AddToCartUpdateView
from .views import CartListView
from .views import BookInCartDeleteView

app_name = 'cart'
urlpatterns = [
    path('add/<int:pk>/', AddToCartUpdateView.as_view(), name='add'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('cart/delete/<int:pk>/', BookInCartDeleteView.as_view(), name='delete')
]

src/order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('checkout/', OrderCreate.as_view(), name='create'),
    path('checkout/thanks/', ThanksView.as_view())


]

src/pj_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('hello.urls')),
    path('books/', include('books.urls')),
    path('', include('catalogs.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from books.models import Book

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Клиент',
        on_delete=models.PROTECT,
        related_name="carts"
    )

    def total_price(self):
        books = self.books.all()
        total = 0
        for book in books:
            total += book.price
        return total


class BookInCart(models.Model):
    book = models.ForeignKey(
        Book,
        verbose_name="Книга",
        on_delete=models.PROTECT,
        related_name="books_in_cart"
    )
    cart = models.ForeignKey(
        Cart,
        verbose_name="Корзина",
        on_delete=models.PROTECT,
        related_name="books"
    )
    quantity = models.IntegerField(
        verbose_name="Количество",
        default=1
    )
    price = models.DecimalField(
        verbose_name="Цена",
        max_digits=8,
        decimal_places=2
    )

    def __str__(self):
        return f"{self.book.name} * {self.quantity}"

src/cart/forms.py
from django.forms import ModelForm
from .models import BookInCart


class BookInCartForm(ModelForm):
    class Meta:
        model = BookInCart
        fields = [
                  'quantity'
                  ]

src/cart/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from .models import BookInCart, Cart
from .forms import BookInCartForm
from books.models import Book
from django.urls import reverse_lazy


# Create your views here.


class AddToCartUpdateView(UpdateView):
    model = BookInCart
    form_class = BookInCartForm
    success_url = reverse_lazy('cart:cart')
    template_name = 'cart/add_to_cart.html'

    def form_valid(self, form,  *args, **kwargs):
        quantity = form.cleaned_data.get('quantity')
        price = self.object.book.price
        new_price = price * quantity
        self.object.price = new_price
        self.object.save()
        return super().form_valid(form)

    def get_object(self):
        book_to_add = self.kwargs.get('pk')
        # проверить существует ли книга
        cart_id = self.request.session.get('cart_id')
        if not cart_id:
            cart = Cart.objects.create(
                user=self.request.user
            )
            self.request.session['cart_id'] = cart.pk
        else:
            cart = Cart.objects.get(pk=cart_id)
        cart_id = self.request.session.get('cart_id')
        book = Book.objects.get(pk=book_to_add)
        book_in_cart, created = BookInCart.objects.get_or_create(
            book=book,
            cart=cart,
            defaults={'price': book.price}
        )
        if not created:
            book_in_cart.price = book.price * (book_in_cart.quantity + 1)
            book_in_cart.quantity = book_in_cart.quantity + 1
            book_in_cart.save()
        return book_in_cart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CartListView(TemplateView):
    model = Cart
    template_name = 'cart/cart.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cart_id = self.request.session.get('cart_id')
        cart = None
        if cart_id:
            cart = Cart.objects.get(pk=cart_id)
        context['cart'] = cart
        return context


class BookInCartDeleteView(DeleteView):
    model = BookInCart
    success_url = '/cart/'
    template_name = 'cart/delete.html'

src/cart/templates/cart/add_to_cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Hello
{% endblock title %}

{% block body %}
<h1>Добавить в корзину</h1>
<h4>Вы добавили книгу: {{ object.book.name }}</h4>
<h4>Доступно к заказу: {{ object.book.in_stock }}</h4>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-info">Отправить</button>
</form>
{% endblock body %}

src/cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Корзина
{% endblock title %}

{% block body %}
<h1>Корзина</h1>
<div class="container">
    <div class="col">
        {% for book_in_cart in cart.books.all %}
        <div class="col-sm">
            <div>{{book_in_cart.book.name}}</div>
            <div>Цена {{book_in_cart.book.price}}</div>
            <div>Количество {{book_in_cart.quantity}}</div>
            <div class="btn-group" role="group" aria-label="Basic example">
                <form action="{% url 'cart:add' book_in_cart.book.pk %}">
                    <button type="submit" class="btn btn-secondary">Изменить</button>
                </form>
                <form action="{% url 'cart:delete' book_in_cart.book.pk %}">
                    <button type="submit" class="btn btn-secondary">Удалить</button>
                </form>
            </div>

        </div>
        <br>
        {% endfor %}
        <h4>Total price: {{ cart.total_price }}</h4>
                <a class="btn btn-primary btn-lg" href="/" role="button">Добавить книгу</a>
                <form action="{% url 'order:create' %}">
                    <button type="submit" class="btn btn-outline-success btn-lg btn-block">Оформить заказ</button>
                </form>
    </div>
</div>
{% endblock body %}

src/cart/templates/cart/delete.html
{% extends 'base.html' %}

{% block title %}
    Удалить книгу из корзины
{% endblock title %}

{% block body %}
<h4>Книга: {{ object.book.name }}</h4>
<form action="" method="POST">
    {% csrf_token %}
    <h1>Уверены что хотите удалить эту книгу из корзины?</h1>
    <button type="submit" class="btn btn-dark">ОФКОРЗ!</button>
</form>
{% endblock body %}